### PR TITLE
Symphonia

### PR DESCRIPTION
**Pull request by mm0hgw**
Notable Things

masterRepoDir

A string naming a local instance of the master working directory for static service.

def blankProposal(branch = None, repoDir = None):

Returns a working directory with the requested branch checked out for editing.

def submitProposal(user, email, repoDir, comment):

Handles proposal submission.

def activeProposals(users, branch = 'master'):

Given a list of users (here used as branch namesakes) return all branches which are both ahead of, and also have no merge conflicts with, the master branch. 

def acceptProposal(branch):

Handle the event that a proposal has collected sufficient acceptance from the group to become a resolution and be merged with the master branch.

### CODE REVIEW

**Comment by mm0hgw** [comment]
def activeProposals(branchfrom = 'master'):

Now doesn't require a list of users.

**Comment by MavropaliasG** [comment]
Thank you very much for this. We'll test the code tomorrow on Sunday. I do have the explanation you gave me in irc.

**Comment by mm0hgw** [comment]
Added

def historicMasterState(t):

Given an epoch time, return a blankProposal() with the state of branch 'master' at time 't'

Say the group bans sandals. If a group member is found to have been wearing sandals, it is necessary to identify the time when they were wearing sandals, and that the ban was in effect at that time, in order to show the member acted contrary to the agreement.

**Comment by mm0hgw** [comment]
I don't think you realise what other 'democratic' tools are lacking.

Democracy is easy to implement. All democracy covers is when acceptProposal() is called, everybody gets one vote, there's a threshhold number which designates acceptance.

This problem has been solved many times before.

Communal decision making is hard. Resolutions can't be retroactive. You can pass a resolution banning the wearing of sandals tomorrow, but you can't retroactively ban the wearing of sandals yesterday. This is a serious enough issue to be a human right according to the UN.

This problem has also been solved many times before, just not on github, because of a misconception that functional communal decision making is a problem for the users, not the coders, and solving the democracy problem, somehow (vigorous hand-waving), solves the communal decision making problem without any effort or consideration required by the coding team.

Imagine if the Austrailian parliament *didn't* have the civil service codify their resolutions into law and left it to the population to figure out the law from their raw polling results. After all, once you've counted the votes, democracy is complete, so obviously democratic communal decision making is complete too. 

Now notice that even the Austrailian parliament is not that drunk. 

Further, @MavropaliasG the users of epitome are coders if words mean something. Words are encoded meaning. A dictionary is a code book that translates words to meanings. A rule/agreement/contract/resolution is information encoded into words. 

The fact that you, personally, understand words, does not stop words from being code. The fact it is possible for words to *not* be understood, demonstrates that they are a code.

If epitome users are *not* coders, then they are restricted from using words to contruct agreements. If they could encode information into words or understand information so encoded, they'd be coders.

Either the users of epitome are coders, or epitome has no users. If epitome has no users, no development is required, because there were never any users for whom to develop.

**Comment by mm0hgw** [comment]
Come to think of it, the vast majority of computer coding is done in human native language.

You don't need to know computer languages until after you know the design specification, specifically:
- what the software *should* do, and
- what the unit tests *should* do to prove the software does what it should.

Once these sets of rules are defined, the definitions can be translated to computer language.

Until that point, knowledge of computer languages is practically useless.

Up to that point, knowledge of how computers work, and how the process to be automated works, is useful.

It does not matter if the language used for the design spec is:
- English
- Japanese
- Klingon
- Welsh
- Xhosa
- Navajo

What matters is that the computer coders can understand the design spec.

When @MavropaliasG is telling me epitome has no space for any users at all, I suspect you don't have a design spec to be understood.

**Comment by mm0hgw** [comment]
On language as code, symphonia has made it into English as 'symphony' and 'symphonic'

Symphonia is literally 'voices together' so this encoding makes sense for a definition of music.

Agreement, on the other hand, comes from the Latin 'gratus' through the French 'agreerment,' literally 'a thing causing pleasure.'

'Accord' also comes from the Latin. Literally it means 'good heart' implying willing faithfulness.

Agreement, Accord and Symphonia may describe very similar things, but the way they encode this concept is vastly different.

**Pull request merged**
